import { DraftPlan } from "@/lib/types";

export const mockApprovePlan: DraftPlan = {
  name: "Build AI Kanban System",
  description: "Step-by-step execution plan generated by AI",
  tasks: [
    {
      title: "Design architecture",
      description: "Define system components and flows",
    },
    {
      title: "Implement backend API",
      description: "Create Go services and handlers",
    },
    {
      title: "Build frontend UI",
      description: "Kanban + chat interface",
    },
  ],
};