package queue

import "github.com/cucumber/godog"

//revive:disable:function-length
//nolint:funlen
func registerQueueSteps(sc *godog.ScenarioContext, state *queueScenario) {
	sc.Step(`^the Queue Daemon is configured with a MaxWorkers limit of (\d+)$`, state.maxWorkersLimit)
	sc.Step(`^the database contains (\d+) tasks in the READY state$`, state.readyTasks)
	sc.Step(`^the Daemon starts and processes the first tick$`, state.daemonTicks)
	sc.Step(`^exactly (\d+) tasks should transition to the QUEUED state$`, state.tasksShouldBeQueued)
	sc.Step(`^the internal semaphore should report (\d+) available slots$`, state.semaphoreAvailable)
	sc.Step(`^the next tick should ignore the remaining (\d+) tasks$`, state.nextTickIgnores)
	sc.Step(`^1 worker finishes its task and releases the slot$`, state.oneWorkerFinishes)
	sc.Step(`^the next tick should pick exactly (\d+) new task from the database$`, state.nextTickPicks)
	sc.Step(`^the Circuit Breaker is in the CLOSED state$`, state.breakerClosed)
	sc.Step(`^a mock AI Gateway is configured to return ErrLLMUnreachable$`, state.gatewayUnreachable)
	sc.Step(`^3 separate workers fail their tasks due to this error$`, state.threeWorkersFailOutage)
	sc.Step(`^the Circuit Breaker should transition to the OPEN state$`, state.breakerShouldBeOpen)
	sc.Step(`^the first outage tasks should be READY and the trip task should be handed to HUMAN$`, state.outageTasksReadyThenHumanHandoff)
	sc.Step(`^the Daemon should pause polling the database for new tasks$`, state.daemonPausesPolling)
	sc.Step(`^the Circuit Breaker is in the OPEN state$`, state.breakerOpen)
	sc.Step(`^the configured timeout period has elapsed$`, state.breakerTimeoutElapsed)
	sc.Step(`^the Daemon ticks$`, state.daemonTicks)
	sc.Step(`^the Circuit Breaker should transition to HALF_OPEN$`, state.breakerShouldBeHalfOpen)
	sc.Step(`^the Daemon should pick exactly 1 READY task to test the connection$`, state.oneProbeTask)
	sc.Step(`^that test task succeeds$`, state.testTaskSucceeds)
	sc.Step(`^the Circuit Breaker should transition to CLOSED$`, state.breakerShouldBeClosed)
	sc.Step(`^normal polling should resume$`, state.normalPollingResumes)
	sc.Step(`^a task is in the READY state with a RetryCount of (\d+)$`, state.readyTaskWithRetries)
	sc.Step(`^the Maximum Retry Limit is set to (\d+)$`, state.maxRetryLimit)
	sc.Step(`^a worker processes the task and the Sandbox returns ExitCode: 1 \(Failure\)$`, state.workerSeesSandboxFailure)
	sc.Step(`^the task's RetryCount should increment to (\d+)$`, state.taskRetryCountShouldBe)
	sc.Step(`^the task should transition to the FAILED_REQUIRES_HUMAN state$`, state.taskShouldBeFailedRequiresHuman)
	sc.Step(`^the system should emit a POISON_PILL_HANDOFF event$`, state.poisonPillHandoffEmitted)
	sc.Step(`^the Daemon should never pick up this task again automatically$`, state.failedTaskNotPicked)
	sc.Step(`^the database contains a task in the RUNNING state with os_process_id: (\d+)$`, state.runningTaskWithPID)
	sc.Step(`^the operating system confirms that PID (\d+) does not exist$`, state.pidDoesNotExist)
	sc.Step(`^the agentd start command initiates the Boot Sequence$`, state.bootSequence)
	sc.Step(`^the Ghost Reconciler should detect the discrepancy$`, state.ghostDetected)
	sc.Step(`^the task should be reverted to the READY state$`, state.taskShouldBeReady)
	sc.Step(`^the os_process_id should be set to NULL$`, state.pidShouldBeNull)
	sc.Step(`^a system event log should be recorded stating "Recovered Ghost Task"$`, state.recoveryEventLogged)
	sc.Step(`^the operating system confirms that PID (\d+) is actively running$`, state.pidIsAlive)
	sc.Step(`^the task should remain in the RUNNING state$`, state.taskShouldRemainRunning)
	sc.Step(`^the Ghost Reconciler should not modify the task$`, state.ghostNotModified)
	sc.Step(`^the Daemon is running$`, state.daemonIsRunning)
	sc.Step(`^a Worker is currently running a Sandbox process$`, state.workerRunningSandbox)
	sc.Step(`^the Go application receives an OS Interrupt signal \(SIGINT\)$`, state.osInterrupt)
	sc.Step(`^the root context should be cancelled$`, state.rootContextCancelled)
	sc.Step(`^the Sandbox should catch the context cancellation and send a SIGKILL to the sleep 100 process$`, state.sandboxCaughtCancel)
	sc.Step(`^the Go application should exit with code 0 only after the worker has safely released its resources$`, state.appExitsAfterRelease)
}
